### ISSUE TITLE
Move ambushGUI to it's own project

### ISSUE THREAD

**Issue by jentfoo** [threadly/ambush#10]
Right now ambushGUI is directory that is compiled from a subdirectory inside ambush.  It does share from the ambush build script.  It is NOT included in the ambush artifact published, it is expected anyone who wants to use the gui should compile it themselves.

So the question is should it be in the same git project like it is currently, or should we fork it out into it's own repo.  No matter what due to the need for native code (swt), I do NOT plan to publish it's artifacts to maven.

@lwahlmeier let me know your opinion on if we should move it out or keep it as is, knowing it makes no difference on the aritfact size.

**Comment by jentfoo** [comment]
I was thinking about this morning, and decided that this should in fact be moved to its own repo.  I will work on making that change before the 0.1.0 release.

**Comment by lwahlmeier** [comment]
@jentfoo I thought about this a little when I saw it come in, imo it should either be its own repo or project, which one does not matter much to me.

**Comment by jentfoo** [comment]
Thanks for the feedback luke.  I went ahead and took care of this real quick!
